// Datos de ejemplo completos para PraxisLex

export const MOCK_CLIENTS = [
  {
    id: "cli_01",
    nombre: "Juan Pérez Santana",
    cedula: "001-1234567-8",
    email: "juan.perez@example.com",
    telefono: "+1 809 555 0101",
    direccion: "Av. Winston Churchill #1502, Santo Domingo",
    casosActivos: 2,
    fechaRegistro: "15 Ene 2025",
    ultimaActividad: "Hace 2 días",
    tipoPersona: "Física",
  },
  {
    id: "cli_02",
    nombre: "Ana María Martínez Gómez",
    cedula: "001-2345678-9",
    email: "ana.martinez@example.com",
    telefono: "+1 809 555 0202",
    direccion: "Calle El Conde #254, Zona Colonial",
    casosActivos: 1,
    fechaRegistro: "03 Feb 2025",
    ultimaActividad: "Hace 5 días",
    tipoPersona: "Física",
  },
  {
    id: "cli_03",
    nombre: "Carlos Alberto García Fernández",
    cedula: "001-3456789-0",
    email: "cgarcia@example.com",
    telefono: "+1 809 555 0303",
    direccion: "Av. 27 de Febrero #312, Santiago",
    casosActivos: 1,
    fechaRegistro: "20 Mar 2025",
    ultimaActividad: "Hace 1 semana",
    tipoPersona: "Física",
  },
  {
    id: "cli_04",
    nombre: "Laura Rodríguez Méndez",
    cedula: "001-4567890-1",
    email: "laura.r@example.com",
    telefono: "+1 809 555 0404",
    direccion: "Calle Proyecto #45, La Romana",
    casosActivos: 1,
    fechaRegistro: "10 Abr 2025",
    ultimaActividad: "Hace 3 días",
    tipoPersona: "Física",
  },
  {
    id: "cli_05",
    nombre: "Bufete López & Asociados SRL",
    cedula: "RNC: 131-12345-6",
    email: "contacto@lopezasoc.do",
    telefono: "+1 809 555 0505",
    direccion: "Torre Empresarial, Piso 12, Piantini",
    casosActivos: 1,
    fechaRegistro: "05 May 2025",
    ultimaActividad: "Hace 2 semanas",
    tipoPersona: "Jurídica",
  },
  {
    id: "cli_06",
    nombre: "Importaciones del Caribe SA",
    cedula: "RNC: 131-23456-7",
    email: "legal@importcaribe.com",
    telefono: "+1 809 555 0606",
    direccion: "Zona Franca Industrial, Haina",
    casosActivos: 3,
    fechaRegistro: "18 Jun 2025",
    ultimaActividad: "Hoy",
    tipoPersona: "Jurídica",
  },
];

export const MOCK_CASES = [
  {
    id: "cas_01",
    numero: "2025-00123",
    titulo: "Cobro de pesos",
    cliente: "Juan Pérez Santana",
    clienteId: "cli_01",
    materia: "Civil",
    juzgado: "Primera Instancia del Distrito Nacional",
    sala: "Sala Civil",
    etapa: "demanda" as const,
    responsables: ["María Arias"],
    monto: 500000,
    hechos: "Incumplimiento de contrato de suministro de mercancías...",
    fecha: "05 Oct 2025",
    proximaAudiencia: "15 Nov 2025",
  },
  {
    id: "cas_02",
    numero: "2025-00115",
    titulo: "Desalojo por falta de pago",
    cliente: "Ana María Martínez Gómez",
    clienteId: "cli_02",
    materia: "Civil",
    juzgado: "Juzgado de Paz del Distrito Nacional",
    sala: "Sala 2",
    etapa: "pruebas" as const,
    responsables: ["María Arias"],
    monto: 180000,
    hechos: "Arrendamiento vencido con 6 meses de mora...",
    fecha: "28 Sep 2025",
    proximaAudiencia: "08 Nov 2025",
  },
  {
    id: "cas_03",
    numero: "2024-00892",
    titulo: "Despido injustificado",
    cliente: "Carlos Alberto García Fernández",
    clienteId: "cli_03",
    materia: "Laboral",
    juzgado: "Tribunal Superior Laboral del Distrito Nacional",
    sala: "Sala Laboral",
    etapa: "contestacion" as const,
    responsables: ["José Ramírez"],
    monto: 850000,
    hechos: "Terminación de relación laboral sin causa justificada...",
    fecha: "15 Ago 2025",
    proximaAudiencia: "22 Nov 2025",
  },
  {
    id: "cas_04",
    numero: "2025-00045",
    titulo: "Divorcio por incompatibilidad",
    cliente: "Laura Rodríguez Méndez",
    clienteId: "cli_04",
    materia: "Familia",
    juzgado: "Primera Instancia del Distrito Nacional",
    sala: "Sala de Familia",
    etapa: "sentencia" as const,
    responsables: ["María Arias"],
    monto: null,
    hechos: "Solicitud de divorcio por incompatibilidad de caracteres...",
    fecha: "10 Feb 2025",
    proximaAudiencia: null,
  },
  {
    id: "cas_05",
    numero: "2024-00654",
    titulo: "Cobro de honorarios profesionales",
    cliente: "Bufete López & Asociados SRL",
    clienteId: "cli_05",
    materia: "Comercial",
    juzgado: "Cámara Civil y Comercial del Distrito Nacional",
    sala: "Sala Comercial",
    etapa: "apelacion" as const,
    responsables: ["José Ramírez"],
    monto: 2500000,
    hechos: "Servicios profesionales prestados sin pago...",
    fecha: "03 Jun 2024",
    proximaAudiencia: "30 Nov 2025",
  },
  {
    id: "cas_06",
    numero: "2025-00201",
    titulo: "Incumplimiento contractual importación",
    cliente: "Importaciones del Caribe SA",
    clienteId: "cli_06",
    materia: "Comercial",
    juzgado: "Primera Instancia de Santo Domingo",
    sala: "Sala Civil y Comercial",
    etapa: "demanda" as const,
    responsables: ["María Arias", "José Ramírez"],
    monto: 3200000,
    hechos: "Incumplimiento de contrato de importación de equipos...",
    fecha: "01 Oct 2025",
    proximaAudiencia: "12 Nov 2025",
  },
];

export const MOCK_JURISPRUDENCE = [
  {
    id: "jur_01",
    numero: "SCJ-3ra-2020-123",
    organo: "Suprema Corte de Justicia",
    sala: "Tercera Sala",
    fecha: "12 Mar 2020",
    titulo: "Responsabilidad contractual por incumplimiento",
    sumario:
      "Se reitera criterio sobre la necesidad de demostrar el daño real y directo en casos de incumplimiento contractual. El demandante debe probar tanto la existencia del contrato como el incumplimiento y el perjuicio sufrido.",
    materia: "Civil",
    url: "https://poderjudicial.gob.do/consulta-sentencias/scj-3ra-2020-123",
  },
  {
    id: "jur_02",
    numero: "SCJ-1ra-2019-045",
    organo: "Suprema Corte de Justicia",
    sala: "Primera Sala",
    fecha: "22 May 2019",
    titulo: "Desahucio en arrendamiento comercial",
    sumario:
      "Criterio establecido sobre plazos de desahucio en contratos comerciales y requisitos de notificación. El propietario debe dar aviso previo conforme a lo establecido en el contrato.",
    materia: "Civil",
    url: "https://poderjudicial.gob.do/consulta-sentencias/scj-1ra-2019-045",
  },
  {
    id: "jur_03",
    numero: "TL-DN-2021-089",
    organo: "Tribunal Superior Laboral DN",
    sala: "Sala Laboral",
    fecha: "15 Sep 2021",
    titulo: "Despido injustificado - Prueba de causa justa",
    sumario:
      "Establece que la carga de la prueba en casos de despido corresponde al empleador demostrar la causa justa. El trabajador debe ser indemnizado si no se prueba la falta grave.",
    materia: "Laboral",
    url: "https://poderjudicial.gob.do/consulta-sentencias/tl-dn-2021-089",
  },
  {
    id: "jur_04",
    numero: "TC-0256-2022",
    organo: "Tribunal Constitucional",
    sala: "Pleno",
    fecha: "08 Dic 2022",
    titulo: "Amparo - Derecho a la tutela judicial efectiva",
    sumario:
      "Se establece que el derecho a la tutela judicial efectiva comprende el acceso a los tribunales y el derecho a obtener una decisión motivada, fundamentada y pronunciada en plazo razonable.",
    materia: "Constitucional",
    url: "https://tribunalconstitucional.gob.do/sentencias/tc-0256-2022",
  },
  {
    id: "jur_05",
    numero: "TST-2020-078",
    organo: "Tribunal Superior de Tierras",
    sala: "Sala Principal",
    fecha: "18 Nov 2020",
    titulo: "Saneamiento - Prescripción adquisitiva",
    sumario:
      "Criterio sobre requisitos de la posesión continuada, pública y pacífica para adquirir por prescripción en materia de tierras. Se requieren 20 años de posesión ininterrumpida.",
    materia: "Tierras",
    url: "https://poderjudicial.gob.do/consulta-sentencias/tst-2020-078",
  },
];
