project_id = "hpeyqttxzrqctrefjlfq"

[functions.generate-legal-doc]
verify_jwt = true

[functions.documents-generate]
verify_jwt = false

[functions.jurisprudence-search]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true
