project_id = "hpeyqttxzrqctrefjlfq"

[functions.generate-legal-doc]
verify_jwt = true

[functions.documents-generate]
verify_jwt = true

[functions.jurisprudence-search]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.send-client-invitation]
verify_jwt = true

[functions.generate-embedding]
verify_jwt = true

[functions.search-jurisprudence-rag]
verify_jwt = true

[functions.process-legal-model]
verify_jwt = true

